// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using MudBlazorWebAppTest.ApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MudBlazorWebAppTest.ApiClient.Api.People.NewHiresWithSince
{
    /// <summary>
    /// Builds and executes requests for operations under \api\People\NewHires(Since={since})
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NewHiresWithSinceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.People.NewHiresWithSince.NewHiresWithSinceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        /// <param name="since">The date and time since people were hired.</param>
        public NewHiresWithSinceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter, DateTimeOffset? since = default) : base(requestAdapter, "{+baseurl}/api/People/NewHires(Since={since})?api-version={api%2Dversion}{&count*,orderby*,select*,skip*,top*}", pathParameters)
        {
            if (since != null) PathParameters.Add("since", since);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.People.NewHiresWithSince.NewHiresWithSinceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NewHiresWithSinceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/People/NewHires(Since={since})?api-version={api%2Dversion}{&count*,orderby*,select*,skip*,top*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets the new hires since the specified date.
        /// </summary>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Models.PersonIEnumerableODataValue"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MudBlazorWebAppTest.ApiClient.Models.PersonIEnumerableODataValue?> GetAsync(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.People.NewHiresWithSince.NewHiresWithSinceRequestBuilder.NewHiresWithSinceRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MudBlazorWebAppTest.ApiClient.Models.PersonIEnumerableODataValue> GetAsync(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.People.NewHiresWithSince.NewHiresWithSinceRequestBuilder.NewHiresWithSinceRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MudBlazorWebAppTest.ApiClient.Models.PersonIEnumerableODataValue>(requestInfo, global::MudBlazorWebAppTest.ApiClient.Models.PersonIEnumerableODataValue.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets the new hires since the specified date.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.People.NewHiresWithSince.NewHiresWithSinceRequestBuilder.NewHiresWithSinceRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.People.NewHiresWithSince.NewHiresWithSinceRequestBuilder.NewHiresWithSinceRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Api.People.NewHiresWithSince.NewHiresWithSinceRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MudBlazorWebAppTest.ApiClient.Api.People.NewHiresWithSince.NewHiresWithSinceRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MudBlazorWebAppTest.ApiClient.Api.People.NewHiresWithSince.NewHiresWithSinceRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets the new hires since the specified date.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class NewHiresWithSinceRequestBuilderGetQueryParameters 
        {
            /// <summary>The requested API version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api%2Dversion")]
            public string? ApiVersion { get; set; }
#nullable restore
#else
            [QueryParameter("api%2Dversion")]
            public string ApiVersion { get; set; }
#endif
            /// <summary>Indicates whether the total count of items within a collection are returned in the result.</summary>
            [QueryParameter("count")]
            public bool? Count { get; set; }
            /// <summary>Specifies the order in which items are returned. The maximum number of expressions is 5. The allowed properties are: firstName, lastName.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderby")]
            public string? Orderby { get; set; }
#nullable restore
#else
            [QueryParameter("orderby")]
            public string Orderby { get; set; }
#endif
            /// <summary>Limits the properties returned in the result.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("select")]
            public string? Select { get; set; }
#nullable restore
#else
            [QueryParameter("select")]
            public string Select { get; set; }
#endif
            /// <summary>Excludes the specified number of items of the queried collection from the result.</summary>
            [QueryParameter("skip")]
            public int? Skip { get; set; }
            /// <summary>Limits the number of items returned from a collection. The maximum value is 100.</summary>
            [QueryParameter("top")]
            public int? Top { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class NewHiresWithSinceRequestBuilderGetRequestConfiguration : RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.People.NewHiresWithSince.NewHiresWithSinceRequestBuilder.NewHiresWithSinceRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
