// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MudBlazorWebAppTest.ApiClient.Api.Products.Item.Supplier.Item.Ref;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MudBlazorWebAppTest.ApiClient.Api.Products.Item.Supplier.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Products\{key}\supplier\{relatedKey}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithRelatedKeyItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Ref property</summary>
        public global::MudBlazorWebAppTest.ApiClient.Api.Products.Item.Supplier.Item.Ref.RefRequestBuilder Ref
        {
            get => new global::MudBlazorWebAppTest.ApiClient.Api.Products.Item.Supplier.Item.Ref.RefRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Products.Item.Supplier.Item.WithRelatedKeyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRelatedKeyItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Products/{key}/supplier/{relatedKey}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Products.Item.Supplier.Item.WithRelatedKeyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRelatedKeyItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Products/{key}/supplier/{relatedKey}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
