// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MudBlazorWebAppTest.ApiClient.Api.Acme;
using MudBlazorWebAppTest.ApiClient.Api.GetSalesTaxRateWithPostalCode;
using MudBlazorWebAppTest.ApiClient.Api.Orders;
using MudBlazorWebAppTest.ApiClient.Api.People;
using MudBlazorWebAppTest.ApiClient.Api.Products;
using MudBlazorWebAppTest.ApiClient.Api.Suppliers;
using MudBlazorWebAppTest.ApiClient.Api.UserSettings;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MudBlazorWebAppTest.ApiClient.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Acme property</summary>
        public global::MudBlazorWebAppTest.ApiClient.Api.Acme.AcmeRequestBuilder Acme
        {
            get => new global::MudBlazorWebAppTest.ApiClient.Api.Acme.AcmeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Orders property</summary>
        public global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder Orders
        {
            get => new global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The People property</summary>
        public global::MudBlazorWebAppTest.ApiClient.Api.People.PeopleRequestBuilder People
        {
            get => new global::MudBlazorWebAppTest.ApiClient.Api.People.PeopleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Products property</summary>
        public global::MudBlazorWebAppTest.ApiClient.Api.Products.ProductsRequestBuilder Products
        {
            get => new global::MudBlazorWebAppTest.ApiClient.Api.Products.ProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Suppliers property</summary>
        public global::MudBlazorWebAppTest.ApiClient.Api.Suppliers.SuppliersRequestBuilder Suppliers
        {
            get => new global::MudBlazorWebAppTest.ApiClient.Api.Suppliers.SuppliersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The UserSettings property</summary>
        public global::MudBlazorWebAppTest.ApiClient.Api.UserSettings.UserSettingsRequestBuilder UserSettings
        {
            get => new global::MudBlazorWebAppTest.ApiClient.Api.UserSettings.UserSettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
        /// <summary>
        /// Builds and executes requests for operations under \api\GetSalesTaxRate(PostalCode={postalCode})
        /// </summary>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Api.GetSalesTaxRateWithPostalCode.GetSalesTaxRateWithPostalCodeRequestBuilder"/></returns>
        /// <param name="postalCode">The postal code to get the sales tax for.</param>
        public global::MudBlazorWebAppTest.ApiClient.Api.GetSalesTaxRateWithPostalCode.GetSalesTaxRateWithPostalCodeRequestBuilder GetSalesTaxRateWithPostalCode(int? postalCode)
        {
            _ = postalCode ?? throw new ArgumentNullException(nameof(postalCode));
            return new global::MudBlazorWebAppTest.ApiClient.Api.GetSalesTaxRateWithPostalCode.GetSalesTaxRateWithPostalCodeRequestBuilder(PathParameters, RequestAdapter, postalCode);
        }
    }
}
#pragma warning restore CS0618
