// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using MudBlazorWebAppTest.ApiClient.Api.Orders.Count;
using MudBlazorWebAppTest.ApiClient.Api.Orders.Item;
using MudBlazorWebAppTest.ApiClient.Api.Orders.MostExpensive;
using MudBlazorWebAppTest.ApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MudBlazorWebAppTest.ApiClient.Api.Orders
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Orders
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrdersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Count property</summary>
        public global::MudBlazorWebAppTest.ApiClient.Api.Orders.Count.CountRequestBuilder Count
        {
            get => new global::MudBlazorWebAppTest.ApiClient.Api.Orders.Count.CountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The MostExpensive property</summary>
        public global::MudBlazorWebAppTest.ApiClient.Api.Orders.MostExpensive.MostExpensiveRequestBuilder MostExpensive
        {
            get => new global::MudBlazorWebAppTest.ApiClient.Api.Orders.MostExpensive.MostExpensiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the MudBlazorWebAppTest.ApiClient.api.Orders.item collection</summary>
        /// <param name="position">The requested order identifier.</param>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.WithKeyItemRequestBuilder"/></returns>
        public global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.WithKeyItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("key", position);
                return new global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.WithKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the MudBlazorWebAppTest.ApiClient.api.Orders.item collection</summary>
        /// <param name="position">The requested order identifier.</param>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.WithKeyItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.WithKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("key", position);
                return new global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.WithKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrdersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Orders?api-version={api%2Dversion}{&count*,select*,skip*,top*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrdersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Orders?api-version={api%2Dversion}{&count*,select*,skip*,top*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves all orders.
        /// </summary>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Models.OrderIEnumerableODataValue"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MudBlazorWebAppTest.ApiClient.Models.OrderIEnumerableODataValue?> GetAsync(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder.OrdersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MudBlazorWebAppTest.ApiClient.Models.OrderIEnumerableODataValue> GetAsync(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder.OrdersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MudBlazorWebAppTest.ApiClient.Models.OrderIEnumerableODataValue>(requestInfo, global::MudBlazorWebAppTest.ApiClient.Models.OrderIEnumerableODataValue.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Places a new order.
        /// </summary>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Models.Order"/></returns>
        /// <param name="body">Represents an order.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MudBlazorWebAppTest.ApiClient.Models.Order?> PostAsync(global::MudBlazorWebAppTest.ApiClient.Models.Order body, Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder.OrdersRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MudBlazorWebAppTest.ApiClient.Models.Order> PostAsync(global::MudBlazorWebAppTest.ApiClient.Models.Order body, Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder.OrdersRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::MudBlazorWebAppTest.ApiClient.Models.Order>(requestInfo, global::MudBlazorWebAppTest.ApiClient.Models.Order.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves all orders.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder.OrdersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder.OrdersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Places a new order.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Represents an order.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::MudBlazorWebAppTest.ApiClient.Models.Order body, Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder.OrdersRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::MudBlazorWebAppTest.ApiClient.Models.Order body, Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder.OrdersRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/api/Orders?api-version={api%2Dversion}{&select*}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, application/json;odata.metadata=full, application/json;odata.metadata=full;odata.streaming=false, application/json;odata.metadata=full;odata.streaming=true, application/json;odata.metadata=minimal, application/json;odata.metadata=minimal;odata.streaming=false, application/json;odata.metadata=minimal;odata.streaming=true, application/json;odata.metadata=none, application/json;odata.metadata=none;odata.streaming=false, application/json;odata.metadata=none;odata.streaming=true, application/json;odata.streaming=false, application/json;odata.streaming=true, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json;odata.streaming=true", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves all orders.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrdersRequestBuilderGetQueryParameters 
        {
            /// <summary>The requested API version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api%2Dversion")]
            public string? ApiVersion { get; set; }
#nullable restore
#else
            [QueryParameter("api%2Dversion")]
            public string ApiVersion { get; set; }
#endif
            /// <summary>Indicates whether the total count of items within a collection are returned in the result.</summary>
            [QueryParameter("count")]
            public bool? Count { get; set; }
            /// <summary>Limits the properties returned in the result. The allowed properties are: id, createdDate, customer, description, lineItems.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("select")]
            public string? Select { get; set; }
#nullable restore
#else
            [QueryParameter("select")]
            public string Select { get; set; }
#endif
            /// <summary>Excludes the specified number of items of the queried collection from the result.</summary>
            [QueryParameter("skip")]
            public int? Skip { get; set; }
            /// <summary>Limits the number of items returned from a collection. The maximum value is 100.</summary>
            [QueryParameter("top")]
            public int? Top { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrdersRequestBuilderGetRequestConfiguration : RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder.OrdersRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Places a new order.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrdersRequestBuilderPostQueryParameters 
        {
            /// <summary>The requested API version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api%2Dversion")]
            public string? ApiVersion { get; set; }
#nullable restore
#else
            [QueryParameter("api%2Dversion")]
            public string ApiVersion { get; set; }
#endif
            /// <summary>Limits the properties returned in the result. The allowed properties are: id, createdDate, customer, description, lineItems.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("select")]
            public string? Select { get; set; }
#nullable restore
#else
            [QueryParameter("select")]
            public string Select { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OrdersRequestBuilderPostRequestConfiguration : RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.OrdersRequestBuilder.OrdersRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
