// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MudBlazorWebAppTest.ApiClient.Api.Acme.Products.Item;
using MudBlazorWebAppTest.ApiClient.Api.Acme.Products.Ref;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MudBlazorWebAppTest.ApiClient.Api.Acme.Products
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Acme\products
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Ref property</summary>
        public global::MudBlazorWebAppTest.ApiClient.Api.Acme.Products.Ref.RefRequestBuilder Ref
        {
            get => new global::MudBlazorWebAppTest.ApiClient.Api.Acme.Products.Ref.RefRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the MudBlazorWebAppTest.ApiClient.api.Acme.products.item collection</summary>
        /// <param name="position">The related entity identifier.</param>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Acme.Products.Item.WithRelatedKeyItemRequestBuilder"/></returns>
        public global::MudBlazorWebAppTest.ApiClient.Api.Acme.Products.Item.WithRelatedKeyItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("relatedKey", position);
                return new global::MudBlazorWebAppTest.ApiClient.Api.Acme.Products.Item.WithRelatedKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the MudBlazorWebAppTest.ApiClient.api.Acme.products.item collection</summary>
        /// <param name="position">The related entity identifier.</param>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Acme.Products.Item.WithRelatedKeyItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::MudBlazorWebAppTest.ApiClient.Api.Acme.Products.Item.WithRelatedKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("relatedKey", position);
                return new global::MudBlazorWebAppTest.ApiClient.Api.Acme.Products.Item.WithRelatedKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Acme.Products.ProductsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Acme/products", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Acme.Products.ProductsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Acme/products", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
