// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using MudBlazorWebAppTest.ApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MudBlazorWebAppTest.ApiClient.Api.Orders.Item.Rate
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Orders\{key}\Rate
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RateRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.Rate.RateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RateRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Orders/{key}/Rate?api-version={api%2Dversion}{&select*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.Rate.RateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RateRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Orders/{key}/Rate?api-version={api%2Dversion}{&select*}", rawUrl)
        {
        }
        /// <summary>
        /// Rates an order.
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(global::MudBlazorWebAppTest.ApiClient.Models.OrdersRateParameters body, Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.Rate.RateRequestBuilder.RateRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(global::MudBlazorWebAppTest.ApiClient.Models.OrdersRateParameters body, Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.Rate.RateRequestBuilder.RateRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Rates an order.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::MudBlazorWebAppTest.ApiClient.Models.OrdersRateParameters body, Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.Rate.RateRequestBuilder.RateRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::MudBlazorWebAppTest.ApiClient.Models.OrdersRateParameters body, Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.Rate.RateRequestBuilder.RateRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json;odata.streaming=true", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.Rate.RateRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.Rate.RateRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.Rate.RateRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Rates an order.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RateRequestBuilderPostQueryParameters 
        {
            /// <summary>The requested API version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api%2Dversion")]
            public string? ApiVersion { get; set; }
#nullable restore
#else
            [QueryParameter("api%2Dversion")]
            public string ApiVersion { get; set; }
#endif
            /// <summary>Limits the properties returned in the result.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("select")]
            public string? Select { get; set; }
#nullable restore
#else
            [QueryParameter("select")]
            public string Select { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RateRequestBuilderPostRequestConfiguration : RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.Item.Rate.RateRequestBuilder.RateRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
