// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MudBlazorWebAppTest.ApiClient.Api.GetSalesTaxRateWithPostalCode
{
    /// <summary>
    /// Builds and executes requests for operations under \api\GetSalesTaxRate(PostalCode={postalCode})
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetSalesTaxRateWithPostalCodeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.GetSalesTaxRateWithPostalCode.GetSalesTaxRateWithPostalCodeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="postalCode">The postal code to get the sales tax for.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetSalesTaxRateWithPostalCodeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter, int? postalCode = default) : base(requestAdapter, "{+baseurl}/api/GetSalesTaxRate(PostalCode={postalCode}){?select*}", pathParameters)
        {
            if (postalCode != null) PathParameters.Add("postalCode", postalCode);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.GetSalesTaxRateWithPostalCode.GetSalesTaxRateWithPostalCodeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetSalesTaxRateWithPostalCodeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/GetSalesTaxRate(PostalCode={postalCode}){?select*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets the sales tax for a postal code.
        /// </summary>
        /// <returns>A <see cref="double"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<double?> GetAsync(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.GetSalesTaxRateWithPostalCode.GetSalesTaxRateWithPostalCodeRequestBuilder.GetSalesTaxRateWithPostalCodeRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<double?> GetAsync(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.GetSalesTaxRateWithPostalCode.GetSalesTaxRateWithPostalCodeRequestBuilder.GetSalesTaxRateWithPostalCodeRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<double?>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets the sales tax for a postal code.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.GetSalesTaxRateWithPostalCode.GetSalesTaxRateWithPostalCodeRequestBuilder.GetSalesTaxRateWithPostalCodeRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.GetSalesTaxRateWithPostalCode.GetSalesTaxRateWithPostalCodeRequestBuilder.GetSalesTaxRateWithPostalCodeRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json;odata.metadata=minimal;odata.streaming=true");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Api.GetSalesTaxRateWithPostalCode.GetSalesTaxRateWithPostalCodeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MudBlazorWebAppTest.ApiClient.Api.GetSalesTaxRateWithPostalCode.GetSalesTaxRateWithPostalCodeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MudBlazorWebAppTest.ApiClient.Api.GetSalesTaxRateWithPostalCode.GetSalesTaxRateWithPostalCodeRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets the sales tax for a postal code.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetSalesTaxRateWithPostalCodeRequestBuilderGetQueryParameters 
        {
            /// <summary>Limits the properties returned in the result.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("select")]
            public string? Select { get; set; }
#nullable restore
#else
            [QueryParameter("select")]
            public string Select { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetSalesTaxRateWithPostalCodeRequestBuilderGetRequestConfiguration : RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.GetSalesTaxRateWithPostalCode.GetSalesTaxRateWithPostalCodeRequestBuilder.GetSalesTaxRateWithPostalCodeRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
