// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MudBlazorWebAppTest.ApiClient.Models
{
    /// <summary>
    /// Represents the line item on an order.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LineItem : IParsable
    {
        /// <summary>Gets or sets the line item description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Gets or sets a value indicating whether the line item is fulfilled.</summary>
        public bool? Fulfilled { get; set; }
        /// <summary>Gets or sets the line item number.</summary>
        public int? Number { get; set; }
        /// <summary>Gets or sets the line item quantity.</summary>
        public int? Quantity { get; set; }
        /// <summary>Gets or sets the line item unit price.</summary>
        public double? UnitPrice { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Models.LineItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MudBlazorWebAppTest.ApiClient.Models.LineItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MudBlazorWebAppTest.ApiClient.Models.LineItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "fulfilled", n => { Fulfilled = n.GetBoolValue(); } },
                { "number", n => { Number = n.GetIntValue(); } },
                { "quantity", n => { Quantity = n.GetIntValue(); } },
                { "unitPrice", n => { UnitPrice = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("fulfilled", Fulfilled);
            writer.WriteIntValue("number", Number);
            writer.WriteIntValue("quantity", Quantity);
            writer.WriteDoubleValue("unitPrice", UnitPrice);
        }
    }
}
#pragma warning restore CS0618
