// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MudBlazorWebAppTest.ApiClient.Models
{
    /// <summary>
    /// Represents an order.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Order : IParsable
    {
        /// <summary>Gets or sets the date and time when the order was created.</summary>
        public DateTimeOffset? CreatedDate { get; set; }
        /// <summary>Gets or sets the name of the ordering customer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Customer { get; set; }
#nullable restore
#else
        public string Customer { get; set; }
#endif
        /// <summary>Gets or sets a description for the order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Gets or sets the date and time when the order becomes effective.</summary>
        public DateTimeOffset? EffectiveDate { get; set; }
        /// <summary>Gets or sets the unique identifier for the order.</summary>
        public int? Id { get; set; }
        /// <summary>Gets a list of line items in the order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MudBlazorWebAppTest.ApiClient.Models.LineItem>? LineItems { get; private set; }
#nullable restore
#else
        public List<global::MudBlazorWebAppTest.ApiClient.Models.LineItem> LineItems { get; private set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Models.Order"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MudBlazorWebAppTest.ApiClient.Models.Order CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MudBlazorWebAppTest.ApiClient.Models.Order();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdDate", n => { CreatedDate = n.GetDateTimeOffsetValue(); } },
                { "customer", n => { Customer = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "effectiveDate", n => { EffectiveDate = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "lineItems", n => { LineItems = n.GetCollectionOfObjectValues<global::MudBlazorWebAppTest.ApiClient.Models.LineItem>(global::MudBlazorWebAppTest.ApiClient.Models.LineItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdDate", CreatedDate);
            writer.WriteStringValue("customer", Customer);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("effectiveDate", EffectiveDate);
            writer.WriteIntValue("id", Id);
        }
    }
}
#pragma warning restore CS0618
