// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MudBlazorWebAppTest.ApiClient.Models
{
    /// <summary>
    /// Represents a person.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Person : IParsable
    {
        /// <summary>Gets or sets the email address for a person.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Gets or sets the first name of a person.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>Represents an address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MudBlazorWebAppTest.ApiClient.Models.Address? HomeAddress { get; set; }
#nullable restore
#else
        public global::MudBlazorWebAppTest.ApiClient.Models.Address HomeAddress { get; set; }
#endif
        /// <summary>Gets or sets the unique identifier for a person.</summary>
        public int? Id { get; set; }
        /// <summary>Gets or sets the last name of a person.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>Gets or sets the telephone number for a person.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>Represents an address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MudBlazorWebAppTest.ApiClient.Models.Address? WorkAddress { get; set; }
#nullable restore
#else
        public global::MudBlazorWebAppTest.ApiClient.Models.Address WorkAddress { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Models.Person"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MudBlazorWebAppTest.ApiClient.Models.Person CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MudBlazorWebAppTest.ApiClient.Models.Person();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "email", n => { Email = n.GetStringValue(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "homeAddress", n => { HomeAddress = n.GetObjectValue<global::MudBlazorWebAppTest.ApiClient.Models.Address>(global::MudBlazorWebAppTest.ApiClient.Models.Address.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "workAddress", n => { WorkAddress = n.GetObjectValue<global::MudBlazorWebAppTest.ApiClient.Models.Address>(global::MudBlazorWebAppTest.ApiClient.Models.Address.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteObjectValue<global::MudBlazorWebAppTest.ApiClient.Models.Address>("homeAddress", HomeAddress);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteStringValue("phone", Phone);
            writer.WriteObjectValue<global::MudBlazorWebAppTest.ApiClient.Models.Address>("workAddress", WorkAddress);
        }
    }
}
#pragma warning restore CS0618
