// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using MudBlazorWebAppTest.ApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MudBlazorWebAppTest.ApiClient.Api.Orders.MostExpensive
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Orders\MostExpensive
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MostExpensiveRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Orders.MostExpensive.MostExpensiveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MostExpensiveRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Orders/MostExpensive?api-version={api%2Dversion}{&select*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Orders.MostExpensive.MostExpensiveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MostExpensiveRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Orders/MostExpensive?api-version={api%2Dversion}{&select*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets the most expensive order.
        /// </summary>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Models.Order"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MudBlazorWebAppTest.ApiClient.Models.Order?> GetAsync(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.MostExpensive.MostExpensiveRequestBuilder.MostExpensiveRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MudBlazorWebAppTest.ApiClient.Models.Order> GetAsync(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.MostExpensive.MostExpensiveRequestBuilder.MostExpensiveRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MudBlazorWebAppTest.ApiClient.Models.Order>(requestInfo, global::MudBlazorWebAppTest.ApiClient.Models.Order.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets the most expensive order.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.MostExpensive.MostExpensiveRequestBuilder.MostExpensiveRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.MostExpensive.MostExpensiveRequestBuilder.MostExpensiveRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MudBlazorWebAppTest.ApiClient.Api.Orders.MostExpensive.MostExpensiveRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MudBlazorWebAppTest.ApiClient.Api.Orders.MostExpensive.MostExpensiveRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MudBlazorWebAppTest.ApiClient.Api.Orders.MostExpensive.MostExpensiveRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets the most expensive order.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MostExpensiveRequestBuilderGetQueryParameters 
        {
            /// <summary>The requested API version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api%2Dversion")]
            public string? ApiVersion { get; set; }
#nullable restore
#else
            [QueryParameter("api%2Dversion")]
            public string ApiVersion { get; set; }
#endif
            /// <summary>Limits the properties returned in the result. The allowed properties are: id, createdDate, customer, description, lineItems.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("select")]
            public string? Select { get; set; }
#nullable restore
#else
            [QueryParameter("select")]
            public string Select { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MostExpensiveRequestBuilderGetRequestConfiguration : RequestConfiguration<global::MudBlazorWebAppTest.ApiClient.Api.Orders.MostExpensive.MostExpensiveRequestBuilder.MostExpensiveRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
