<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.17.1" />
    <PackageReference Include="CodeBeam.MudBlazor.Extensions" Version="8.3.0" />
    <PackageReference Include="Microsoft.Kiota.Authentication.Azure" Version="1.21.0" />
    <PackageReference Include="Microsoft.Kiota.Bundle" Version="1.21.0" />
    <PackageReference Include="MudBlazor" Version="8.*" />
    <PackageReference Include="Simple.OData.Client" Version="6.0.1" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="ViewModels\" />
  </ItemGroup>
</Project>