<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MudBlazor.Northwind</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="MyFile.txt">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MyFile.tt</DependentUpon>
    </Compile>
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Blazored.FluentValidation" Version="2.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.10" />
    <PackageReference Include="MudBlazor" Version="8.*" />
    <PackageReference Include="MudBlazor.Extensions" Version="8.14.0" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Northwind.Client.Lib\Northwind.Client.Lib.csproj" />
    <ProjectReference Include="..\Shared.Models\Shared.Models.csproj" />
  </ItemGroup>


  <ItemGroup>
    <T4Runtime Include="RuntimeTextTemplate.tt">
      <Generator>MsBuild:Compile</Generator>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </T4Runtime>
    <None Update="MyFile.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>MyFile.txt</LastGenOutput>
    </None>
    <None Update="T4\EntitiesRepository.tt">
      <LastGenOutput>EntitiesRepository.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="T4\MudFormTemplate.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>MudFormTemplate.txt</LastGenOutput>
    </None>
    <None Update="T4\MudFormTemplate.txt">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MudFormTemplate.tt</DependentUpon>
    </None>
    <None Update="T4\RuntimeTextTemplate.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>RuntimeTextTemplate.cs</LastGenOutput>
    </None>
    <None Update="T4\TextTemplate.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>TextTemplate.txt</LastGenOutput>
    </None>
    <None Update="T4\TextTemplate.txt">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TextTemplate.tt</DependentUpon>
    </None>
  </ItemGroup>



  <ItemGroup>
    <Folder Include="Components\Employees\" />
  </ItemGroup>

  
  <ItemGroup>
    <None Include="MyFile.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MyFile.tt</DependentUpon>
    </None>
  </ItemGroup>


  <ItemGroup>
    <Compile Update="Components\Pages\MudFormTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MudFormTemplate.tt</DependentUpon>
    </Compile>
    <Compile Update="T4\RuntimeTextTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>RuntimeTextTemplate.tt</DependentUpon>
    </Compile>
  </ItemGroup>


  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
</Project>